version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: noizee_db_final
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "2549"
      MYSQL_DATABASE: "DA"
    ports:
      - "3307:3306"  # Map ra cổng 3307 để tránh đụng MySQL có sẵn
    volumes:
      - db_data:/var/lib/mysql
      # Dòng dưới này sẽ tự động chạy file .sql khi DB khởi tạo lần đầu
      - ./sql_script:/docker-entrypoint-initdb.d

volumes:
  db_data: